use super::*;

mod brave;
mod buddy;
mod chrom;
mod daisy;
mod diddy;
mod edge;
mod falco;
mod ganon;
mod koopa;
mod koopajr;
mod krool;
mod littlemac;
mod lucas;
mod lucario;
mod luigi;
mod mario;
mod mariod;
mod mewtwo;
mod miifighter;
mod miigunner;
mod palutena;
mod pfushigisou;
mod pikmin;
mod plizardon;
mod purin;
mod pzenigame;
mod richter;
mod ridley;
mod roy;
mod shizue;
mod sonic;
mod trail;
mod wolf;

pub fn install(agent: &mut Agent) {
    brave::install(agent);
    buddy::install(agent);
    chrom::install(agent);
    daisy::install(agent);
    diddy::install(agent);
    edge::install(agent);
    falco::install(agent);
    ganon::install(agent);
    koopa::install(agent);
    koopajr::install(agent);
    krool::install(agent);
    littlemac::install(agent);
    lucas::install(agent);
    lucario::install(agent);
    luigi::install(agent);
    mario::install(agent);
    mariod::install(agent);
    mewtwo::install(agent);
    miifighter::install(agent);
    miigunner::install(agent);
    palutena::install(agent);
    pfushigisou::install(agent);
    pikmin::install(agent);
    plizardon::install(agent);
    pzenigame::install(agent);
    purin::install(agent);
    richter::install(agent);
    ridley::install(agent);
    roy::install(agent);
    shizue::install(agent);
    sonic::install(agent);
    trail::install(agent);
    wolf::install(agent);
}