on: 
  push:
    branches:
      - dev

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
 
      # tag push
      - uses: jefflinse/pr-semver-bump@v1
        name: Bump and Tag Version
        id: push_tag
        with:
          mode: bump
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          minor-label: semver:feature
          patch-label: semver:patch

      # make fake asset
      - name: make asset
        shell: bash
        run: |
          echo lol > asset.txt

      ## upload asset
      #- name: Upload binaries to release
      #  uses: svenstaro/upload-release-action@v2
      #  with:
      #    repo_token: ${{ secrets.GITHUB_TOKEN }}
      #    file: asset*
      #    file_glob: true
      #    asset_name: the_asset
      #    tag: ${{ steps.push_tag.outputs.version }}
      #    overwrite: true
      #    body: "This is my release text"