on: 
  push:
    branches:
      - dev

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
 
      # tag push
      - uses: jefflinse/pr-semver-bump@v1
        name: Bump and Tag Version
        id: push_tag
        with:
          mode: bump
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          minor-label: semver:feature
          patch-label: semver:patch
          with-v: true

      - name: checkout version
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
  
        # github changelog
      - name: "Generate release changelog"
        id: github_changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          sinceTag: ${{ steps.push_tag.outputs.old-version }}
          token: ${{ secrets.GITHUB_TOKEN }} 
      - name: view changelog
        id: output_changelog
        run: |
          echo "${{steps.github_changelog.outputs.changelog}}"

      # make fake asset
      - name: make asset
        shell: bash
        run: |
          echo "lol" > asset.txt

      # upload asset
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: asset*
          prerelease: true
          file_glob: true
          asset_name: the_asset
          release_name: ${{ steps.push_tag.outputs.version }}-nightly
          tag: ${{ steps.push_tag.outputs.version }}
          overwrite: true
          body: ${{ steps.github_changelog.outputs.changelog }}