on: 
  push:
    branches:
      - dev

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
 
      # tag push
      - uses: jefflinse/pr-semver-bump@v1
        name: Bump and Tag Version
        id: push_tag
        with:
          mode: bump
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          minor-label: semver:feature
          patch-label: semver:patch
          with-v: true

      # make fake asset
      - name: make asset
        shell: bash
        run: |
          echo lol > asset.txt

      - name: checkout version
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      # build changelog
      - name: Build Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # upload asset
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: asset*
          file_glob: true
          asset_name: the_asset
          tag: ${{ steps.push_tag.outputs.version }}
          overwrite: true
          body: ${{ steps.changelog.outputs.changelog }}